### ISSUE TITLE
fsck.mergerfs fails on dereferencing symlinks with nonexistent target

### ISSUE THREAD

**Issue by d10n** [trapexit/mergerfs#184]
I don't know what the behavior should be, but I don't think the current behavior is right. I have lots of dead-end symlinks that I don't intend to fix.

Example:
```
# fsck.mergerfs /media/data
Traceback (most recent call last):
  File "/usr/bin/fsck.mergerfs", line 58, in main
    check_consistancy(fullpath,args.verbose,fix)
  File "/usr/bin/fsck.mergerfs", line 70, in check_consistancy
    paths = xattr.getxattr(fullpath,"user.mergerfs.allpaths").split('\0')
  File "/usr/lib/python2.7/site-packages/xattr/__init__.py", line 178, in getxattr
    return xattr(f).get(attr, options=symlink and XATTR_NOFOLLOW or 0)
  File "/usr/lib/python2.7/site-packages/xattr/__init__.py", line 68, in get
    return self._call(_getxattr, _fgetxattr, name, 0, 0, options | self.options)
  File "/usr/lib/python2.7/site-packages/xattr/__init__.py", line 59, in _call
    return name_func(self.value, *args)
  File "/usr/lib/python2.7/site-packages/xattr/lib.py", line 642, in _getxattr
    raise error(path)
  File "/usr/lib/python2.7/site-packages/xattr/lib.py", line 628, in error
    raise IOError(errno, strerror, path)
IOError: [Errno 2] No such file or directory: '/media/data/etc/init.d/alsa-mixer-save'
/media/data is not a mergerfs device

# ls -l /media/data/v/init.d/alsa-mixer-save
lrwxrwxrwx 1 me users 21 Apr  2  2011 /media/data/etc/init.d/alsa-mixer-save -> /lib/init/upstart-job

# ls -l /lib/init/upstart-job
ls: cannot access /lib/init/upstart-job: No such file or directory
```

**Comment by trapexit** [comment]
Moved: https://github.com/trapexit/mergerfs-tools/issues/5
